apiVersion: v1
kind: Service
metadata:
  labels:
    app: media
  name: nzbget-service
spec:
  ports:
  - nodePort: 
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: media
  type: NodePort