apiVersion: v1
kind: Service
metadata:
  labels:
    app: media
  name: media-service
spec:
  ports:
  - nodePort: 
    port: 8989
    protocol: TCP
    targetPort: 8989
  - nodePort: 
    port: 5050
    protocol: TCP
    targetPort: 5050
  - nodePort: 
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: media
  type: NodePort