---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: media
spec:
  containers:
    - name: sonarr
      image: linuxserver\sonarr
      ports:
        - containerPort: 8989
      env:
        - name: TZ
          value: America\Chicago
        - name: PUID
          value: 1006
        - name: PGID
          value: 1005