apiVersion: v1
kind: Service
metadata:
  labels:
    app: media
  name: sonarr-service
spec:
  ports:
  - nodePort: 
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: media
  type: NodePort