apiVersion: v1
kind: Service
metadata:
  labels:
    app: media
  name: couchpotato-service
spec:
  ports:
  - nodePort: 
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: media
  type: NodePort